// *******************************************
//          W A F - AUTO GENERATED CODE       
// Do not edit! File is regularly overwritten.
// *******************************************


using System;
using WAF.Common;
using WAF.Definition;
using WAF.Engine;
using WAF.Engine.Content;
using WAF.Engine.Content.Native;
using WAF.Engine.Query;
using WAF.Engine.Query.Advanced;
using WAF.Engine.Property;
using WAF.Data;
using WAF.Data.Query;
using WAF.Data.Query.RelatudeFishingShop;
using WAF.Data.Content;
using WAF.Data.DataValue;
using WAF.Presentation.Web;

namespace WAF.Engine.Content.RelatudeFishingShop {
    [Serializable]
    public partial class Article: WAF.Engine.Content.Native.ArticleBase {
        LongStringPropertyValue _autoGeneratedMetaDescription;
        public virtual string AutoGeneratedMetaDescription {
        get { return LongStringPropertyValue.GetValue(WAFID.GetDataValueId("5d371b5c-1f73-40f9-887d-e098c2c58a6e"), ref _autoGeneratedMetaDescription, this.Session, this.ContentId, this.ContentData.DataValueById, this.ContentParentPath); }
        set { EnsureContentDataIndependence(); LongStringPropertyValue.SetValue(WAFID.GetDataValueId("5d371b5c-1f73-40f9-887d-e098c2c58a6e"), ref _autoGeneratedMetaDescription, this.Session, this.ContentId, this.ContentData.DataValueById, value); }
        }
      
        public override IContent AddCulture(int lcid) {
            return _WAFSession.AddCulture<Article>(NodeId, lcid);
        }
        public override IContent AddRevision(int revision) {
            return _WAFSession.AddRevision<Article>(NodeId, revision);
        }
        public override IContent AddContent(int lcid, int revision) {
            return _WAFSession.AddContent<Article>(NodeId, lcid, revision);
        }
        ///<summary>
        ///The internal Id of the Ontology content class
        ///</summary>
        public static new int ContentClassId {
            get {
                return WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745");
            }
        }

        public static int PropertyIdAutoGeneratedMetaDescription {
            get {
                return WAFID.GetPropertyId("d20d57b4-2653-4411-9c04-cf90276e7b1e");
            }
        }

        public static int DataValueIdAutoGeneratedMetaDescriptionAutoGeneratedMetaDescription {
            get {
                return WAFID.GetDataValueId("5d371b5c-1f73-40f9-887d-e098c2c58a6e");
            }
        }

        public override object GetProperty(int propertyId) {
            EnsureContentDataIndependence();
            if (propertyId == WAFID.GetPropertyId("d20d57b4-2653-4411-9c04-cf90276e7b1e")) {
                object init = AutoGeneratedMetaDescription;
                return _autoGeneratedMetaDescription;
            }
            return base.GetProperty(propertyId);
        }
        protected override void ResetPropertyValues() {
            _autoGeneratedMetaDescription = null;
            base.ResetPropertyValues();
        }
    }
}
namespace WAF.Data.Query.RelatudeFishingShop {
    public abstract class SqlArticle {
        public static SqlTable Table {
            get {
                return new SqlTable("article", WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public abstract partial class Field {
            public static SqlFieldInteger ContentId {
                get {
                    return new SqlFieldPrimaryInteger("content_id", Table);
                }
            }

            public static SqlFieldLongString AutoGeneratedMetaDescription {
                get {
                    return new SqlFieldLongString("auto_generated_meta_description", Table, WAFID.GetDataValueId("5d371b5c-1f73-40f9-887d-e098c2c58a6e"));
                }
            }

        }
    }
    public class SqlAliasArticle : SqlAlias {
        public SqlAliasArticle()
            : base(SqlArticle.Table) {
        }
        public SqlExpressionFieldInteger ContentId {
            get {
                return new SqlExpressionFieldInteger(SqlArticle.Field.ContentId, this);
            }
        }

        public SqlExpressionFieldLongString AutoGeneratedMetaDescription {
            get {
                return new SqlExpressionFieldLongString(SqlArticle.Field.AutoGeneratedMetaDescription, this);
            }
        }

    }
}
namespace WAF.Engine.Query.RelatudeFishingShop {
    [System.Serializable]
    public partial class AqlArticle{
        public static AqlPropertyInteger NodeId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Node.Id, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyShortString Guid  {
            get {
                return new AqlPropertyShortString(Sql.Field.Node.Guid, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger SiteId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Node.SiteId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger ContentId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Content.ContentId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger Revision  {
            get {
                return new AqlPropertyInteger(Sql.Field.Content.Revision, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger AuthorId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Content.AuthorId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger TemplateId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Content.TemplateId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger ModuleId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Content.ModuleId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger LCID  {
            get {
                return new AqlPropertyInteger(Sql.Field.NodeCsd.LCID, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyBoolean IsDerived  {
            get {
                return new AqlPropertyBoolean(Sql.Field.Content.IsDerived, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyBoolean IsPublished  {
            get {
                return new AqlPropertyBoolean(Sql.Field.Node.IsPublished, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyBoolean Hidden  {
            get {
                return new AqlPropertyBoolean(Sql.Field.Node.Hidden, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyBoolean IsRevisionDeleted {
            get {
                return new AqlPropertyBoolean(Sql.Field.Content.IsDeleted, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyBoolean IsNodeDeleted {
            get {
                return new AqlPropertyBoolean(Sql.Field.Node.IsDeleted, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyInteger ContentClassId  {
            get {
                return new AqlPropertyInteger(Sql.Field.Node.ContentClassId, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyDateTime CreateDate  {
            get {
                return new AqlPropertyDateTime(Sql.Field.Content.CreateDate, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyDateTime ChangeDate  {
            get {
                return new AqlPropertyDateTime(Sql.Field.Content.ChangeDate, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyDateTime PublishDate  {
            get {
                return new AqlPropertyDateTime(Sql.Field.Content.PublishDate, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyDateTime ReleaseDate  {
            get {
                return new AqlPropertyDateTime(Sql.Field.Content.ReleaseDate, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyDateTime RetainDate  {
            get {
                return new AqlPropertyDateTime(Sql.Field.Content.RetainDate, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyShortString Name  {
            get {
                return new AqlPropertyShortString(Sql.Field.Content.Name, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")); 
            }
        }

        public static AqlPropertyLongString AutoGeneratedMetaDescription {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.RelatudeFishingShop.SqlArticle.Field.AutoGeneratedMetaDescription, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyLongString Ingress {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.Native.SqlArticleBase.Field.Ingress, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyShortString IngressImage_ingress_filename {
            get {
                return new AqlPropertyShortString(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_filename, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyShortString IngressImage_ingress_type_name {
            get {
                return new AqlPropertyShortString(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_type_name, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyShortString IngressImage_ingress_extension {
            get {
                return new AqlPropertyShortString(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_extension, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyFloat IngressImage_ingress_bytes {
            get {
                return new AqlPropertyFloat(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_bytes, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyLongString IngressImage_ingress_info {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_info, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyInteger IngressImage_ingress_reference {
            get {
                return new AqlPropertyInteger(WAF.Data.Query.Native.SqlArticleBase.Field.IngressImage_ingress_reference, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyLongString BodyContent {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.Native.SqlArticleBase.Field.BodyContent, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyShortString TemplatePath {
            get {
                return new AqlPropertyShortString(WAF.Data.Query.Native.SqlHierarchicalContent.Field.TemplatePath, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyShortString MetaTitle {
            get {
                return new AqlPropertyShortString(WAF.Data.Query.Native.SqlHierarchicalContent.Field.MetaTitle, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean AutoMetaTitle {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.AutoMetaTitle, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyLongString MetaDescription {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.Native.SqlHierarchicalContent.Field.MetaDescription, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean AutoMetaDescription {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.AutoMetaDescription, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyLongString MetaKeywords {
            get {
                return new AqlPropertyLongString(WAF.Data.Query.Native.SqlHierarchicalContent.Field.MetaKeywords, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean AutoMetaKeywords {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.AutoMetaKeywords, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyRelation ContentTags {
            get {
                return new AqlPropertyRelation( WAFID.GetPropertyId("a4e4d56c-8ff9-4ede-9232-094e72398668"), new AqlAliasRelation(new WAF.Engine.Query.Native.AqlAliasHierarchicalContent(), new WAF.Engine.Query.Native.AqlAliasContentTag(), WAF.Engine.Query.Native.AqlRelTaxonomyHierarchical.Relation));
            }
        }

        public static AqlPropertyRelation Children {
            get {
                return new AqlPropertyRelation( WAFID.GetPropertyId("cc90eccd-1d77-40c8-aab7-5262842a66e2"), new AqlAliasRelation(new WAF.Engine.Query.Native.AqlAliasHierarchicalContent(), new WAF.Engine.Query.Native.AqlAliasHierarchicalContent(), WAF.Engine.Query.Native.AqlRelHierarchical.Relation));
            }
        }

        public static AqlPropertyRelation Parent {
            get {
                return new AqlPropertyRelation( WAFID.GetPropertyId("a1eca898-8f93-4522-a46c-669c56af9b55"), new AqlAliasRelation(new WAF.Engine.Query.Native.AqlAliasHierarchicalContent(), new WAF.Engine.Query.Native.AqlAliasHierarchicalContent(), WAF.Engine.Query.Native.AqlRelHierarchical.Relation));
            }
        }

        public static AqlPropertyBoolean ShowInTree {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.ShowInTree, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean ShowInMenu {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.ShowInMenu, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyInteger DefaultReadAccessOnChildren {
            get {
                return new AqlPropertyInteger(WAF.Data.Query.Native.SqlHierarchicalContent.Field.DefaultReadAccessOnChildren, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyInteger DefaultEditAccessOnChildren {
            get {
                return new AqlPropertyInteger(WAF.Data.Query.Native.SqlHierarchicalContent.Field.DefaultEditAccessOnChildren, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyInteger DefaultPublishAccessOnChildren {
            get {
                return new AqlPropertyInteger(WAF.Data.Query.Native.SqlHierarchicalContent.Field.DefaultPublishAccessOnChildren, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyInteger AddChildAccess {
            get {
                return new AqlPropertyInteger(WAF.Data.Query.Native.SqlHierarchicalContent.Field.AddChildAccess, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean DefaultInTree {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.DefaultInTree, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean DefaultInMenu {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.DefaultInMenu, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

        public static AqlPropertyBoolean ExcludeFromIndex {
            get {
                return new AqlPropertyBoolean(WAF.Data.Query.Native.SqlHierarchicalContent.Field.ExcludeFromIndex, WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745"));
            }
        }

    }
    [System.Serializable]
    public class AqlAliasArticle
        : WAF.Engine.Query.Native.AqlAliasArticleBase{

        public AqlAliasArticle()
            : base(WAFID.GetContentClassId("89d055b1-ed59-4634-8c36-3ecdccba6745")) {

        }

        public AqlAliasArticle(int contentClassId)
            : base(contentClassId) {

        }

        public AqlExpressionPropertyLongString AutoGeneratedMetaDescription {
            get {
                return new AqlExpressionPropertyLongString(AqlArticle.AutoGeneratedMetaDescription, this);
            }
        }

    }
}
